# Generated by Django 3.1.5 on 2021-01-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210112_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(max_length=5000),
        ),
    ]
